### ISSUE TITLE
代码开源

### ISSUE THREAD

**Issue by xiaoludiver** [alexhe101/FourierISP#1]
作者您好，你的工作非常interesting，请问什么时候开源代码

**Comment by alexhe101** [comment]
感谢您对我们工作的关注，下周内会开源代码

**Comment by alexhe101** [comment]
代码已公开

**Comment by jamesli1618** [comment]
您好，请问何时公开模型权重？谢谢。

**Comment by alexhe101** [comment]
> 您好，请问何时公开模型权重？谢谢。

这个是在公司实习期间做的，权重不在我手上，可能不太方便公开;下载zrrdataset 复现一下应该比较容易，我当时每张卡12G，用了4张卡，大概一到2天可以训练完

**Comment by jamesli1618** [comment]
好的，感谢！
