### ISSUE TITLE
Visualization code of Figure 2

### ISSUE THREAD

**Issue by jamesli1618** [alexhe101/FourierISP#3]
您好，请问能否把paper里的Figure 2的visualization code也上传一下？我直接visualize phase和amplitude，得不到paper里展示的结果。谢谢！

**Comment by alexhe101** [comment]
您好！
Fig2 不是对phase和amplitude进行visualize的结果，是傅里叶变换后，删去振幅或相位，再逆变换为空间域的结果。
可视化待我整理后会上传。

**Comment by alexhe101** [comment]
代码已上传 https://github.com/alexhe101/FourierISP/blob/main/fourier.py
