### ISSUE TITLE
MAI dataset

### ISSUE THREAD

**Issue by Chegva** [alexhe101/FourierISP#4]
请问您是否能吧MAI数据集链接发出来呢

**Comment by alexhe101** [comment]
您好，我们没有相关数据集的发布权限。MAI dataset来自于https://codalab.lisn.upsaclay.fr/competitions/1759, 您可以自行注册后进行下载

**Comment by jamesli1618** [comment]
您好，MAI dataset的training data的官方下载链接已经失效了，请问能否share一下dataset？

**Comment by alexhe101** [comment]
> 您好，MAI dataset的training data的官方下载链接已经失效了，请问能否share一下dataset？

您好，这是我在公司实习期间做的工作，已经离职很久了，手上没有数据；我记得AIM比赛 2022/2021/2020 有一年的下载链接还在，您可以尝试一下这几年的
