### ISSUE TITLE
Figure 2的可视化代码

### ISSUE THREAD

**Issue by TIANLE233** [alexhe101/FourierISP#5]
您好！我希望您上传Figure 2的可视化代码，这对我非常有帮助，我将会引用您的论文

**Comment by alexhe101** [comment]
您好，可以参考https://github.com/alexhe101/FourierISP/blob/main/fourier.py
我还没整理，函数有点多，您可以参照一下，具体的是通过Fourier变换后，把振幅或者相位置为一个常数并逆变换回去即可

**Comment by TIANLE233** [comment]
> 您好，可以参考https://github.com/alexhe101/FourierISP/blob/main/fourier.py 我还没整理，函数有点多，您可以参照一下，具体的是通过Fourier变换后，把振幅或者相位置为一个常数并逆变换回去即可
非常感谢，我研究一下

**Comment by TIANLE233** [comment]
非常感谢，我研究一下
